nelmio_api_doc:
    documentation:
        info:
            title: studyOn.Billing
            description: Billing servise for study-on!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
        